### ISSUE TITLE
unclosed bracked

### ISSUE THREAD

**Issue by Dual-28** [Kaiseriscool/Rip-Alerts#1]
line 72 in sv_rips there's a open bracket with no bracket closing it

**Comment by Dual-28** [comment]
[rips_final] addons/rips_final/lua/autorun/server/sv_rips.lua:107: 'end' expected (to close 'function' at line 72) near '<eof>'

**Comment by Kaiseriscool** [comment]
Randock go test it pal!

**Comment by Kaiseriscool** [comment]
New verison will fix it
